name: rule-of-thumb
channels:
  - conda-forge

dependencies:
  - python==3.10
  - matplotlib
  - jax>=0.4.31
  - quadax~=0.2
  - scipy~=1.13
  - pip
  - pip:
      - netket>=3.14
      - git+https://github.com/davecwright3/PTArcade.git@feat/jax-utilities
